group: deprecated-2017Q2

language: python
python:
- 2.7
- 3.6
- 3.5
- 3.4
- 3.7-dev
- nightly
- pypy
- pypy3
matrix:
  allow_failures:
  - python: 2.7
  - python: pypy
  - python: pypy3
  - python: nightly
  - python: 3.7-dev
services:
- docker
before_install:
- sudo service docker restart ; sleep 10  # https://github.com/travis-ci/travis-ci/issues/4778
- docker run -d --publish=28015:28015 rethinkdb
- docker run -d --publish=8020:8020 --publish=50070:50070 --publish=50010:50010 --publish=50020:50020 --publish=50075:50075 chalimartines/cdh5-pseudo-distributed
install:
- pip install git+https://github.com/jkafader/snakebite@feature/python3-version-string
- pip install -e . --no-input --upgrade
- pip install pytest
script:
- py.test -v tests
notifications:
  slack: internetarchive:PLZQTqR7RpyGNr1jb1TgMqhK

